"use client";
import { Download, Play, FileText, Table2, DollarSign, ClipboardList, Star, Users, ShieldCheck, Layers } from "lucide-react";

const reportTypes = [
  { Icon: DollarSign,   title: "Revenue Report",          desc: "Monthly and annual revenue breakdown by service, zone, and provider.", color: "#eef2ff" },
  { Icon: ClipboardList,title: "Booking Report",           desc: "Detailed booking analytics with status, trends, and cancellations.",   color: "#f0fdf4" },
  { Icon: Star,         title: "Provider Performance",     desc: "Ratings, jobs completed, earnings, and response time metrics.",        color: "#fff7ed" },
  { Icon: Users,        title: "Customer Report",          desc: "Customer acquisition, retention, LTV, and activity analysis.",         color: "#fdf4ff" },
  { Icon: ShieldCheck,  title: "Warranty Report",          desc: "Warranty claims, resolutions, and pending cases overview.",            color: "#eff6ff" },
  { Icon: Layers,       title: "Material Cost Report",     desc: "Material usage, costs, and wastage tracking per project.",             color: "#fef9c3" },
];

const recentReports = [
  { name: "Revenue Report - Dec 2024", by: "Admin", date: "10 Jan 2025", format: "PDF" },
  { name: "Booking Report - Q4 2024", by: "Manager", date: "05 Jan 2025", format: "Excel" },
  { name: "Provider Performance - Dec", by: "Admin", date: "03 Jan 2025", format: "PDF" },
  { name: "Customer Report - Dec 2024", by: "Support", date: "02 Jan 2025", format: "CSV" },
  { name: "Warranty Report - Dec 2024", by: "Operations", date: "01 Jan 2025", format: "PDF" },
];

export default function ReportsPage() {
  const card = { background: "#fff", borderRadius: 12, padding: 24, boxShadow: "0 1px 3px rgba(0,0,0,0.08)", border: "1px solid #f1f5f9" };

  return (
    <div style={{}}>
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, color: "#0f172a", margin: 0 }}>Reports</h1>
        <p style={{ fontSize: 14, color: "#94a3b8", margin: "4px 0 0" }}>Generate and download business reports</p>
      </div>

      {/* Report Type Grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16, marginBottom: 28 }}>
        {reportTypes.map((r) => (
          <div key={r.title} style={{ background: r.color, border: "1px solid #e2e8f0", borderRadius: 12, padding: 24 }}>
            <div style={{ marginBottom: 12 }}><r.Icon size={36} color="#6366f1" /></div>
            <h3 style={{ fontSize: 15, fontWeight: 700, color: "#0f172a", margin: "0 0 8px" }}>{r.title}</h3>
            <p style={{ fontSize: 13, color: "#64748b", margin: "0 0 16px", lineHeight: 1.6 }}>{r.desc}</p>
            <div style={{ display: "flex", gap: 8 }}>
              <button style={{ flex: 1, background: "#6366f1", color: "#fff", border: "none", borderRadius: 8, padding: "9px 0", cursor: "pointer", fontSize: 13, fontWeight: 600, display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }}>
                <Play size={16} /> Generate
              </button>
              <button style={{ background: "#fff", color: "#475569", border: "1px solid #e2e8f0", borderRadius: 8, padding: "9px 14px", cursor: "pointer", fontSize: 13, fontWeight: 600, display: "flex", alignItems: "center", gap: 4 }}>
                <Download size={15} /> Download
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Recent Reports */}
      <div style={card}>
        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#0f172a", margin: "0 0 20px" }}>Recent Reports</h3>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ borderBottom: "1px solid #f1f5f9" }}>
              {["Report Name", "Generated By", "Date", "Format", "Download"].map((h) => (
                <th key={h} style={{ color: "#94a3b8", fontWeight: 600, fontSize: 13, padding: "10px 12px", textAlign: "left" }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {recentReports.map((r) => (
              <tr key={r.name} style={{ borderBottom: "1px solid #f8fafc" }}>
                <td style={{ padding: "14px 12px", fontSize: 14, fontWeight: 600, color: "#0f172a" }}>{r.name}</td>
                <td style={{ padding: "14px 12px", fontSize: 14, color: "#475569" }}>{r.by}</td>
                <td style={{ padding: "14px 12px", fontSize: 14, color: "#475569" }}>{r.date}</td>
                <td style={{ padding: "14px 12px" }}>
                  <span style={{ background: r.format === "PDF" ? "#fee2e2" : r.format === "Excel" ? "#dcfce7" : "#dbeafe", color: r.format === "PDF" ? "#dc2626" : r.format === "Excel" ? "#16a34a" : "#2563eb", borderRadius: 999, padding: "3px 10px", fontSize: 12, fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 4 }}>
                    {r.format === "PDF" ? <FileText size={12} /> : <Table2 size={12} />} {r.format}
                  </span>
                </td>
                <td style={{ padding: "14px 12px" }}>
                  <button style={{ background: "#f1f5f9", border: "none", borderRadius: 6, padding: "6px 12px", cursor: "pointer", color: "#6366f1", fontSize: 13, fontWeight: 600, display: "flex", alignItems: "center", gap: 4 }}>
                    <Download size={15} /> Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

